require 'hoe'

Hoe.plugin :travis

Hoe.spec 'memorandum' do
  developer 'Robert Lude', 'rob@ertlu.de'
  license   'MIT'

  dependency 'ice_nine', '0.11.2'

  dependency 'byebug', '~> 9.0', :dev
  dependency 'rspec',  '~> 3.0', :dev
end
